// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class VoteResultItem {
  final int idxQuestion;
  final int idxSubQuestion;
  final int idxAnswer;
  final BigInt votes;

  const VoteResultItem({
    required this.idxQuestion,
    required this.idxSubQuestion,
    required this.idxAnswer,
    required this.votes,
  });

  @override
  int get hashCode =>
      idxQuestion.hashCode ^
      idxSubQuestion.hashCode ^
      idxAnswer.hashCode ^
      votes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoteResultItem &&
          runtimeType == other.runtimeType &&
          idxQuestion == other.idxQuestion &&
          idxSubQuestion == other.idxSubQuestion &&
          idxAnswer == other.idxAnswer &&
          votes == other.votes;
}
