// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_to_vote_server`, `submit_ballot`

String compileElectionDef({
  required String electionJson,
  required String seed,
}) => RustLib.instance.api.crateApiSimpleCompileElectionDef(
  electionJson: electionJson,
  seed: seed,
);

Future<Uint8List> storeElection({
  required String electionJson,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleStoreElection(
  electionJson: electionJson,
  context: context,
);

Future<void> scanNotes({
  required String hash,
  required int idAccount,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleScanNotes(
  hash: hash,
  idAccount: idAccount,
  context: context,
);

Future<void> scanBallots({
  required String hash,
  required int idAccount,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleScanBallots(
  hash: hash,
  idAccount: idAccount,
  context: context,
);

Future<void> decodeBallots({
  required String hash,
  required String electionSeed,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleDecodeBallots(
  hash: hash,
  electionSeed: electionSeed,
  context: context,
);

Future<void> collectResults({required Context context}) =>
    RustLib.instance.api.crateApiSimpleCollectResults(context: context);

Future<BigInt> getBalance({
  required String hash,
  required int idAccount,
  required int idxQuestion,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleGetBalance(
  hash: hash,
  idAccount: idAccount,
  idxQuestion: idxQuestion,
  context: context,
);

Future<void> vote({
  required String hash,
  required int idAccount,
  required int idxQuestion,
  required String voteContent,
  required BigInt amount,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleVote(
  hash: hash,
  idAccount: idAccount,
  idxQuestion: idxQuestion,
  voteContent: voteContent,
  amount: amount,
  context: context,
);

Future<void> mint({
  required String hash,
  required int idAccount,
  required int idxQuestion,
  required BigInt amount,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleMint(
  hash: hash,
  idAccount: idAccount,
  idxQuestion: idxQuestion,
  amount: amount,
  context: context,
);

Future<void> delegate({
  required String hash,
  required int idAccount,
  required int idxQuestion,
  required String address,
  required BigInt amount,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleDelegate(
  hash: hash,
  idAccount: idAccount,
  idxQuestion: idxQuestion,
  address: address,
  amount: amount,
  context: context,
);

Future<String> getAccountAddress({
  required int idAccount,
  required Context context,
}) => RustLib.instance.api.crateApiSimpleGetAccountAddress(
  idAccount: idAccount,
  context: context,
);
