// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VoteMessage {
    #[prost(oneof = "vote_message::TypeOneof", tags = "1, 2, 3, 4")]
    pub type_oneof: ::core::option::Option<vote_message::TypeOneof>,
}
/// Nested message and enum types in `VoteMessage`.
pub mod vote_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum TypeOneof {
        #[prost(message, tag = "1")]
        AddValidator(super::AddValidator),
        #[prost(message, tag = "2")]
        SetElection(super::SetElection),
        #[prost(uint32, tag = "3")]
        Start(u32),
        #[prost(message, tag = "4")]
        Ballot(super::Ballot),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddValidator {
    #[prost(bytes = "vec", tag = "1")]
    pub pub_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub power: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetElection {
    #[prost(string, tag = "1")]
    pub election: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ballot {
    #[prost(string, tag = "1")]
    pub ballot: ::prost::alloc::string::String,
}
