name: Build Voter
permissions:
  contents: read

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  workflow_call:

jobs:
  build-voter:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_x86_64.tar.gz -o grpcurl.tar.gz
          tar -xzf grpcurl.tar.gz
          sudo mv grpcurl /usr/local/bin/
          sudo npm -g install graphqurl
          NPMBIN=$(npm prefix -g)/bin
          echo "$NPMBIN" >> $GITHUB_PATH
          go install github.com/cometbft/cometbft/cmd/cometbft@v0.38
          GOBIN=$(go env GOPATH)/bin
          echo "$GOBIN" >> $GITHUB_PATH
      - name: Build
        run: |
          cargo build -r
          cometbft init --home node
          cometbft start --home node >/dev/null &
          cp zcv.toml node/
          (cd node; ../target/release/vote-cometbft &)
          sleep 5
          ./tests/submit_election.sh ./tests/test_election
          sleep 5
          ./target/release/voter --election-url "http://localhost:9010" &
          ./tests/voter.sh
